services:
  - type: web
    name: pisa-backend
    runtime: node
    buildCommand: "npm run build"
    startCommand: "npm start"
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: PORT
        value: "10000"
