services:
  - type: web
    name: pisa-backend
    runtime: node
    buildCommand: "cd backend/functions && npm install && npm run build"
    startCommand: "cd backend/functions && node lib/index.js"
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: PORT
        value: "10000"
